# Generated by Django 5.1.1 on 2025-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profileimage/logo.webp', upload_to='profileimage/'),
        ),
    ]
